### ISSUE TITLE
error on ui command.

### ISSUE THREAD

**Issue by sanhar** [TitasGailius/laravel-moonlight#1]
First , this package  looks great . thanks for your work.

I ran this command as Readme described. 

$php artisan ui moonlight --auth

but there is error.

And it even erased 'vendor' folder on my project. 

```sh 
$php artisan ui moonlight --auth

Moonlight authentication scaffolding generated successfully.
Moonlight scaffolding installed successfully.
Please run "composer install && npm install && npm run dev" to update composer packages and compile your fresh scaffolding.
PHP Fatal error:  Uncaught ErrorException: include(/Users/asarha/document/package-laravel-moonlight/vendor/composer/../nunomaduro/collision/src/Provider.php): failed to open stream: No such file or directory in /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/asarha/...', 444, Array)
#1 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(444): include()
#2 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/asarha/...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('NunoMaduro\\Co in /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught ErrorException: include(/Users/asarha/document/package-laravel-moonlight/vendor/composer/../symfony/debug/Exception/FatalErrorException.php): failed to open stream: No such file or directory in /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/asarha/...', 444, Array)
#1 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(444): include()
#2 /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/asarha/...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symf in /Users/asarha/document/package-laravel-moonlight/vendor/composer/ClassLoader.php on line 444
```

**Comment by TitasGailius** [comment]
Hello,

thanks for reporting. Which OS do you use?

It updates the `composer.json` file and deletes the `vendor` directory so you can install the missing composer dependencies with `composer install`.

I'm sure scaffolding got set up correctly either way.
